spring.application.name=SwiftQueue


# --- Database Configuration ---
spring.datasource.url=jdbc:mysql://localhost:3306/swiftqueue
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA Configuration ---
# Use 'update' for development. Use 'validate' or 'none' for production.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- JWT Configuration ---
# Use a strong, randomly generated secret in production and store it as an environment variable
jwt.secret=patel@swift@dubai#queue
# Expiration time in milliseconds (7 days)
jwt.expiration-ms=604800000
